/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ac3a799f-b1bd-4d89-90dd-3d077093d5cb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TQfQZAp1w",
    "aws_user_pools_web_client_id": "616hrrn4hikrujnb364siip7cp",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS"
};


export default awsmobile;
